# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d39ad8d0a9c4827f5f5f9376645ed82d4ea8f34ddc8019a46361380d0b90bcecec9d690ff1c75d0605100a97a0fca0f40aa4ec844dd1e90c4cc7bea76d889f77

test:
  secret_key_base: a807ff26764401fd72c9890960b56ee19b3a4eda2dacf3572b45f95339483e51454e98c5324088f06ff1668738151b4426f5aefdc73e9b41ed544d3664c0f212

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
